//! The asset probe: the final accounting step of `make assets`. It writes
//! `catalog/models.generated.toml` — every installed enemy model, keyed by
//! file stem, valued by its `res://` path. `[[enemy]] model = "<key>"`
//! resolves against this catalog, so a typo or a missing install is a link
//! error naming the culprit — never an invisible drone at runtime. Every
//! catalogued file's geometry is parsed, so a broken export from ANY
//! pipeline step fails the probe, not a run.
//!
//! The output is GENERATED-BUT-COMMITTED (like `VOCABULARY.md`): the game
//! embeds it at compile time, machinery rewrites it, hands never do.
//! Emission goes through the same serde schema the loader reads
//! ([`schema::ModelsFile`]), so the round-trip cannot drift.
//!
//! It also writes `catalog/kits.generated.toml` — each kit's tile/story
//! DERIVED from its assembly recipe (owner 2026-07-05: no authored
//! dimensions anywhere; two hand-transcribed copies had already drifted
//! into folklore). Kit pieces bake their stack position into mesh space,
//! so for a layered kit the story is the TOP layer's y-max (a Top piece
//! spans y 3..5) and the tile is the straight wall's z-range; for a panel
//! kit the pool's uniform square extent is the pitch. The recipes are the
//! wall/panel sets in [`crate::asset_catalog`]; every set of a kit must
//! derive the same grid or the probe fails.
//!
//! Test-gated: the `gltf` parser is a dev-dependency; the probe runs as an
//! `--ignored` writer test (the `regenerate_*` house pattern) from
//! `make assets`.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use crate::asset_catalog::ALL_WALL_SETS;

use super::schema::{EnvironmentsFile, GeneratedKitRaw, GeneratedKitsFile, KitsFile, ModelsFile};

/// Where enemy models install, relative to `godot/`. A new directory in
/// the pipeline gets catalogued by being added here.
const MODEL_DIRS: &[&str] = &["addons/enemies", "addons/quaternius/essentials/enemies"];

/// Where fixed-level environment scenes install, relative to `godot/`.
/// Catalogued into `catalog/environments.generated.toml` — a separate
/// namespace from the enemy models (see [`schema::EnvironmentsFile`]).
const ENVIRONMENT_DIRS: &[&str] = &["addons/environments"];

const GENERATED_HEADER: &str =
    "# GENERATED by `make assets` (the roster probe) — do not edit.\n";

fn repo_root() -> PathBuf {
    Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/../..")).to_path_buf()
}

fn gltf_files(dir: &Path) -> Vec<PathBuf> {
    let mut files: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("{}: unreadable ({e}) — run `make assets`", dir.display()))
        .map(|e| e.expect("dir entry").path())
        .filter(|p| {
            p.extension()
                .is_some_and(|x| x == "glb" || x == "gltf")
        })
        .collect();
    files.sort();
    files
}

/// World-space AABB extents (x, y, z) of a glTF file's default scene.
fn aabb_extents(path: &Path) -> [f32; 3] {
    let (lo, hi) = aabb_bounds(path);
    [hi[0] - lo[0], hi[1] - lo[1], hi[2] - lo[2]]
}

/// Column-major 4×4 compose, matching `gltf::scene::Transform::matrix()`
/// — the one shared home for both glTF walks (bounds and measure).
fn mul(a: [[f32; 4]; 4], b: [[f32; 4]; 4]) -> [[f32; 4]; 4] {
    let mut out = [[0.0; 4]; 4];
    for (c, col) in out.iter_mut().enumerate() {
        for (r, cell) in col.iter_mut().enumerate() {
            *cell = (0..4).map(|k| a[k][r] * b[c][k]).sum();
        }
    }
    out
}

const IDENTITY: [[f32; 4]; 4] = [
    [1.0, 0.0, 0.0, 0.0],
    [0.0, 1.0, 0.0, 0.0],
    [0.0, 0.0, 1.0, 0.0],
    [0.0, 0.0, 0.0, 1.0],
];

/// World-space AABB corners (lo, hi) of a glTF file's default scene:
/// accessor min/max corners composed through the node transforms — bounds
/// come from the JSON, no buffer loading. Kit pieces bake their stack
/// offsets into mesh space (a Top piece SPANS y 3..5), so lo/hi carry
/// assembly information the extents alone lose.
fn aabb_bounds(path: &Path) -> ([f32; 3], [f32; 3]) {
    let doc = gltf::Gltf::open(path)
        .unwrap_or_else(|e| panic!("{}: not a readable glTF ({e})", path.display()))
        .document;
    let mut lo = [f32::INFINITY; 3];
    let mut hi = [f32::NEG_INFINITY; 3];

    fn visit(
        node: gltf::Node,
        parent: [[f32; 4]; 4],
        lo: &mut [f32; 3],
        hi: &mut [f32; 3],
        path: &Path,
    ) {
        let world = mul(parent, node.transform().matrix());
        if let Some(mesh) = node.mesh() {
            for prim in mesh.primitives() {
                let Some(acc) = prim.get(&gltf::Semantic::Positions) else {
                    continue;
                };
                let corner = |v: &serde_json::Value, i: usize| -> f32 {
                    v.get(i).and_then(|x| x.as_f64()).unwrap_or_else(|| {
                        panic!("{}: POSITION accessor without bounds", path.display())
                    }) as f32
                };
                let (min, max) = (
                    acc.min().expect("POSITION min is required by the glTF spec"),
                    acc.max().expect("POSITION max is required by the glTF spec"),
                );
                for cx in [corner(&min, 0), corner(&max, 0)] {
                    for cy in [corner(&min, 1), corner(&max, 1)] {
                        for cz in [corner(&min, 2), corner(&max, 2)] {
                            for i in 0..3 {
                                let p = world[0][i] * cx
                                    + world[1][i] * cy
                                    + world[2][i] * cz
                                    + world[3][i];
                                lo[i] = lo[i].min(p);
                                hi[i] = hi[i].max(p);
                            }
                        }
                    }
                }
            }
        }
        for child in node.children() {
            visit(child, world, lo, hi, path);
        }
    }

    let scene = doc
        .default_scene()
        .or_else(|| doc.scenes().next())
        .unwrap_or_else(|| panic!("{}: no scene", path.display()));
    for node in scene.nodes() {
        visit(node, IDENTITY, &mut lo, &mut hi, path);
    }
    assert!(
        lo[0].is_finite(),
        "{}: no positioned geometry",
        path.display()
    );
    (lo, hi)
}

/// The model catalog: every installed enemy model, geometry-validated.
pub fn model_catalog() -> String {
    let godot = repo_root().join("godot");
    let mut models = BTreeMap::new();
    for rel in MODEL_DIRS {
        for f in gltf_files(&godot.join(rel)) {
            aabb_extents(&f); // a broken export fails the probe, not a run
            let key = f.file_stem().unwrap().to_string_lossy().into_owned();
            let res = format!(
                "res://{}",
                f.strip_prefix(&godot).unwrap().display()
            );
            assert!(
                models.insert(key.clone(), res).is_none(),
                "duplicate model key '{key}' across the install dirs"
            );
        }
    }
    let body = toml::to_string(&ModelsFile { models }).expect("serialize model catalog");
    format!(
        "{GENERATED_HEADER}\
         # Every installed enemy model: key (file stem) -> res:// path.\n\
         # rosters/enemies.toml refers to models by KEY; the linker resolves\n\
         # against this catalog, so a bad reference fails the load, loudly.\n\
         \n{body}"
    )
}

/// The environment catalog: every installed fixed-level environment scene,
/// geometry-validated.
pub fn environment_catalog() -> String {
    let godot = repo_root().join("godot");
    let mut environments = BTreeMap::new();
    for rel in ENVIRONMENT_DIRS {
        for f in gltf_files(&godot.join(rel)) {
            aabb_extents(&f); // a broken export fails the probe, not a run
            let key = f.file_stem().unwrap().to_string_lossy().into_owned();
            let res = format!("res://{}", f.strip_prefix(&godot).unwrap().display());
            assert!(
                environments.insert(key.clone(), res).is_none(),
                "duplicate environment key '{key}' across the install dirs"
            );
        }
    }
    let body =
        toml::to_string(&EnvironmentsFile { environments }).expect("serialize environment catalog");
    format!(
        "{GENERATED_HEADER}\
         # Every installed fixed-level environment: key (file stem) -> res://\n\
         # path. Fixed-paradigm kits refer to environments by KEY; the linker\n\
         # resolves against this catalog, so a bad reference fails the load,\n\
         # loudly.\n\
         \n{body}"
    )
}

/// A res:// path's location on disk.
fn res_to_disk(repo: &Path, res: &str) -> PathBuf {
    repo.join("godot").join(res.trim_start_matches("res://"))
}

/// Fraction of the rectangle `lo..hi` covered by the projected triangles
/// (2D, plate-face space): a 64×64 center-sample rasterization. Slivers —
/// triangles projecting edge-on — cover nothing, so a truss's side faces
/// don't inflate its coverage.
fn face_coverage(tris: &[[[f32; 2]; 3]], lo: [f32; 2], hi: [f32; 2]) -> f32 {
    const N: usize = 64;
    let (w, h) = (hi[0] - lo[0], hi[1] - lo[1]);
    if w <= 0.0 || h <= 0.0 {
        return 0.0;
    }
    let mut covered = vec![false; N * N];
    let sliver = w * h * 1e-6;
    let cell = |x: f32, lo: f32, span: f32| -> f32 { lo + (x + 0.5) * span / N as f32 };
    for t in tris {
        let area2 = (t[1][0] - t[0][0]) * (t[2][1] - t[0][1])
            - (t[2][0] - t[0][0]) * (t[1][1] - t[0][1]);
        if area2.abs() * 0.5 < sliver {
            continue;
        }
        // Only the cells under the triangle's bbox get sampled.
        let (bx0, bx1) = (
            t.iter().map(|v| v[0]).fold(f32::MAX, f32::min),
            t.iter().map(|v| v[0]).fold(f32::MIN, f32::max),
        );
        let (by0, by1) = (
            t.iter().map(|v| v[1]).fold(f32::MAX, f32::min),
            t.iter().map(|v| v[1]).fold(f32::MIN, f32::max),
        );
        let gx0 = (((bx0 - lo[0]) / w * N as f32).floor().max(0.0)) as usize;
        let gx1 = (((bx1 - lo[0]) / w * N as f32).ceil()).min(N as f32) as usize;
        let gy0 = (((by0 - lo[1]) / h * N as f32).floor().max(0.0)) as usize;
        let gy1 = (((by1 - lo[1]) / h * N as f32).ceil()).min(N as f32) as usize;
        for gy in gy0..gy1 {
            for gx in gx0..gx1 {
                if covered[gy * N + gx] {
                    continue;
                }
                let (px, py) = (cell(gx as f32, lo[0], w), cell(gy as f32, lo[1], h));
                let edge = |a: [f32; 2], b: [f32; 2]| -> f32 {
                    (b[0] - a[0]) * (py - a[1]) - (b[1] - a[1]) * (px - a[0])
                };
                let (e0, e1, e2) = (edge(t[0], t[1]), edge(t[1], t[2]), edge(t[2], t[0]));
                let inside = if area2 > 0.0 {
                    e0 >= 0.0 && e1 >= 0.0 && e2 >= 0.0
                } else {
                    e0 <= 0.0 && e1 <= 0.0 && e2 <= 0.0
                };
                if inside {
                    covered[gy * N + gx] = true;
                }
            }
        }
    }
    covered.iter().filter(|c| **c).count() as f32 / (N * N) as f32
}

/// Measure one installed kit piece: world-space triangles are collected
/// through the node transforms, the plate face is the two largest AABB
/// extents, and coverage rasterizes the triangles projected onto it.
/// One measured mesh: everything the census records that comes from the
/// file itself. `detail` is the relief-heavy side along the thin axis —
/// the artist's greeble; `relief` is that verdict's confidence (the
/// mass asymmetry, 0 = symmetric/unmeasurable). The material triplet
/// answers "did the PBR maps survive the pipeline" without opening
/// Blender.
struct Measured {
    face: [f32; 2],
    thick: f32,
    axis: super::schema::ThinAxis,
    detail: crate::room_template::ConnectorFacing,
    relief: f32,
    coverage: f32,
    tris: u32,
    textures: u8,
    metallic: f32,
    roughness: f32,
    mr_map: bool,
    metallic_px: f32,
    rough_px: f32,
}

fn piece_census(path: &Path) -> super::schema::GeneratedPieceRaw {
    let m = measure(path);
    super::schema::GeneratedPieceRaw {
        face: m.face,
        thick: m.thick,
        axis: m.axis,
        relief: m.relief,
        coverage: m.coverage,
        tris: m.tris,
        textures: m.textures,
        metallic: m.metallic,
        roughness: m.roughness,
        mr_map: m.mr_map,
        metallic_px: m.metallic_px,
        rough_px: m.rough_px,
    }
}

/// (positive-side, negative-side) relief mass along `thin`: geometry
/// weighed by its distance BEYOND the base slab — the peak flat-area
/// depth bin. The heavier side is the greeble. Convention-free where
/// the winding sum it replaced read modeling conventions (the bake
/// 5/6/8 oscillation saga); scripts/split-panels.py computes the SAME
/// split, so Transform and probe cannot disagree by construction.
fn relief_split(tris: &[[[f32; 3]; 3]], thin: usize) -> (f32, f32) {
    const BINS: usize = 32;
    let mut lo = f32::INFINITY;
    let mut hi = f32::NEG_INFINITY;
    for t in tris {
        for v in t {
            lo = lo.min(v[thin]);
            hi = hi.max(v[thin]);
        }
    }
    let depth = hi - lo;
    if !depth.is_finite() || depth <= f32::EPSILON {
        return (0.0, 0.0);
    }
    let mut flat = [0.0f32; BINS];
    let mut weighed: Vec<(f32, f32)> = Vec::with_capacity(tris.len());
    for t in tris {
        let e1 = [t[1][0] - t[0][0], t[1][1] - t[0][1], t[1][2] - t[0][2]];
        let e2 = [t[2][0] - t[0][0], t[2][1] - t[0][1], t[2][2] - t[0][2]];
        let cross = [
            e1[1] * e2[2] - e1[2] * e2[1],
            e1[2] * e2[0] - e1[0] * e2[2],
            e1[0] * e2[1] - e1[1] * e2[0],
        ];
        let norm = (cross[0] * cross[0] + cross[1] * cross[1] + cross[2] * cross[2]).sqrt();
        let area = norm / 2.0;
        if area <= 0.0 {
            continue;
        }
        let c = (t[0][thin] + t[1][thin] + t[2][thin]) / 3.0;
        // Only face-on area votes for the base slab: a greeble's side
        // walls are relief, not a candidate base plane.
        let bin = (((c - lo) / depth) * BINS as f32) as usize;
        flat[bin.min(BINS - 1)] += area * (cross[thin].abs() / norm);
        weighed.push((area, c));
    }
    let peak = (0..BINS).max_by(|&a, &b| flat[a].total_cmp(&flat[b])).unwrap();
    let bin_lo = lo + depth * peak as f32 / BINS as f32;
    let bin_hi = lo + depth * (peak + 1) as f32 / BINS as f32;
    let mut pos = 0.0;
    let mut neg = 0.0;
    for (area, c) in weighed {
        pos += area * (c - bin_hi).max(0.0);
        neg += area * (bin_lo - c).max(0.0);
    }
    (pos, neg)
}

/// Mean of channel `offset` across pixels of `stride` bytes, as 0..1;
/// 1.0 (the glTF neutral multiplier) when the channel does not exist.
fn channel_mean(pixels: &[u8], stride: usize, offset: usize) -> f32 {
    if offset >= stride || pixels.len() < stride {
        return 1.0;
    }
    let mut sum = 0u64;
    let mut n = 0u64;
    for px in pixels.chunks_exact(stride) {
        sum += px[offset] as u64;
        n += 1;
    }
    if n == 0 {
        return 1.0;
    }
    sum as f32 / (n as f32 * 255.0)
}

/// Whether a baked file's census record inverts for the kit's authored
/// per-piece flips: every source overridden, or none — a mixed stack
/// has no single artist front to record.
fn override_inversion(sources: &[String], flips: &[String]) -> Result<bool, String> {
    let overridden = sources.iter().filter(|s| flips.contains(s)).count();
    match overridden {
        0 => Ok(false),
        n if n == sources.len() => Ok(true),
        _ => Err(format!(
            "sources {sources:?} mix authored detail_flip pieces with plain ones — \
             no single artist front; author both or neither"
        )),
    }
}

fn variant_census(
    path: &Path,
    declared: &super::schema::ManifestVariantRaw,
    flips: &[String],
) -> super::schema::GeneratedVariantRaw {
    let m = measure(path);
    // The census's `detail` MEANS the artist's front: the measured
    // relief side, inverted for pieces the kit AUTHORS as detailed on
    // their relief-light side.
    let inverted = override_inversion(&declared.sources, flips)
        .unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    super::schema::GeneratedVariantRaw {
        sources: declared.sources.clone(),
        role: declared.role,
        face: m.face,
        thick: m.thick,
        axis: m.axis,
        detail: if inverted { m.detail.opposite() } else { m.detail },
        relief: m.relief,
        coverage: m.coverage,
        stretch: declared.stretch,
        tris: m.tris,
        textures: m.textures,
    }
}

fn measure(path: &Path) -> Measured {
    let (doc, buffers, images) = gltf::import(path)
        .unwrap_or_else(|e| panic!("{}: not an importable glTF ({e})", path.display()));

    let mut tris: Vec<[[f32; 3]; 3]> = Vec::new();
    fn visit(
        node: gltf::Node,
        parent: [[f32; 4]; 4],
        buffers: &[gltf::buffer::Data],
        tris: &mut Vec<[[f32; 3]; 3]>,
    ) {
        let world = mul(parent, node.transform().matrix());
        if let Some(mesh) = node.mesh() {
            for prim in mesh.primitives() {
                let reader = prim.reader(|b| Some(&buffers[b.index()]));
                let Some(pos) = reader.read_positions() else { continue };
                let verts: Vec<[f32; 3]> = pos
                    .map(|p| {
                        let mut out = [0.0; 3];
                        for (i, o) in out.iter_mut().enumerate() {
                            *o = world[0][i] * p[0]
                                + world[1][i] * p[1]
                                + world[2][i] * p[2]
                                + world[3][i];
                        }
                        out
                    })
                    .collect();
                let idx: Vec<u32> = match reader.read_indices() {
                    Some(ix) => ix.into_u32().collect(),
                    None => (0..verts.len() as u32).collect(),
                };
                for tri in idx.chunks_exact(3) {
                    tris.push([
                        verts[tri[0] as usize],
                        verts[tri[1] as usize],
                        verts[tri[2] as usize],
                    ]);
                }
            }
        }
        for child in node.children() {
            visit(child, world, buffers, tris);
        }
    }
    for scene in doc.scenes() {
        for node in scene.nodes() {
            visit(node, IDENTITY, &buffers, &mut tris);
        }
    }
    assert!(!tris.is_empty(), "{}: no triangles", path.display());

    let mut lo = [f32::INFINITY; 3];
    let mut hi = [f32::NEG_INFINITY; 3];
    for t in &tris {
        for v in t {
            for i in 0..3 {
                lo[i] = lo[i].min(v[i]);
                hi[i] = hi[i].max(v[i]);
            }
        }
    }
    let ext = [hi[0] - lo[0], hi[1] - lo[1], hi[2] - lo[2]];
    // The plate's thin axis; the other two are the face, larger first.
    let thin = (0..3).min_by(|&a, &b| ext[a].total_cmp(&ext[b])).unwrap();
    let (u, v) = match thin {
        0 => (1, 2),
        1 => (0, 2),
        _ => (0, 1),
    };
    let (u, v) = if ext[u] >= ext[v] { (u, v) } else { (v, u) };

    // The detail direction: the relief-heavy side along the thin axis —
    // where the artist's greeble is. Ties (a symmetric or featureless
    // plate) break positive, deterministically, on both sides of the
    // pipeline.
    let (relief_pos, relief_neg) = relief_split(&tris, thin);
    use crate::room_template::ConnectorFacing;
    let positive = relief_pos >= relief_neg;
    let detail = match (thin, positive) {
        (0, true) => ConnectorFacing::PosX,
        (0, false) => ConnectorFacing::NegX,
        (1, true) => ConnectorFacing::PosY,
        (1, false) => ConnectorFacing::NegY,
        (2, true) => ConnectorFacing::PosZ,
        _ => ConnectorFacing::NegZ,
    };

    // Material facts, straight from the file. Effective shading is
    // FACTOR × MAP CHANNEL (glTF: roughness rides green, metallic rides
    // blue), so the census records both — factors alone lie in both
    // directions (a matte factor under an absent map, a neutral 1.0
    // factor over a white metal channel).
    let mut metallic = 0.0f32;
    let mut roughness = 1.0f32;
    let mut mr_map = false;
    let mut any_material = false;
    let mut metallic_px = 1.0f32;
    let mut rough_px = 1.0f32;
    let mut maps = 0u32;
    for mat in doc.materials() {
        let pbr = mat.pbr_metallic_roughness();
        any_material = true;
        metallic = metallic.max(pbr.metallic_factor());
        roughness = roughness.min(pbr.roughness_factor());
        if let Some(tex) = pbr.metallic_roughness_texture() {
            mr_map = true;
            let img = &images[tex.texture().source().index()];
            let stride = img.pixels.len() / (img.width as usize * img.height as usize).max(1);
            let (g, b) = (
                channel_mean(&img.pixels, stride, 1),
                channel_mean(&img.pixels, stride, 2),
            );
            // Across materials keep the SHINIEST verdict — one chrome
            // material on a matte piece still glares.
            if maps == 0 || b > metallic_px {
                metallic_px = b;
            }
            if maps == 0 || g < rough_px {
                rough_px = g;
            }
            maps += 1;
        }
    }
    if !any_material {
        metallic = 1.0;
    }

    let flat: Vec<[[f32; 2]; 3]> = tris
        .iter()
        .map(|t| t.map(|p| [p[u], p[v]]))
        .collect();
    let relief_total = relief_pos + relief_neg;
    Measured {
        face: [ext[u], ext[v]],
        thick: ext[thin],
        axis: match thin {
            0 => super::schema::ThinAxis::X,
            1 => super::schema::ThinAxis::Y,
            _ => super::schema::ThinAxis::Z,
        },
        detail,
        relief: if relief_total > 0.0 {
            (relief_pos - relief_neg).abs() / relief_total
        } else {
            0.0
        },
        coverage: face_coverage(&flat, [lo[u], lo[v]], [hi[u], hi[v]]),
        tris: tris.len() as u32,
        textures: doc.images().len().min(u8::MAX as usize) as u8,
        metallic,
        roughness,
        mr_map,
        metallic_px,
        rough_px,
    }
}

/// Derive one kit's grid from its installed meshes. Layered: tile = the
/// straight wall's z-range, story = the top layer's mesh-space y-max
/// (pieces bake their stack position, so the ceiling piece's top IS the
/// story) — every recipe set covering the kit must agree. Panel: the kit
/// is CENSUSED piece by piece (face, thickness, thin axis, coverage,
/// tris, textures)
/// and the grid is the largest square plate face — square plates define
/// the cell; conversion snaps provider slop onto them (split-panels.py).
fn derive_kit_grid(
    repo: &Path,
    key: &str,
    kit: &super::schema::KitRaw,
) -> GeneratedKitRaw {
    use super::schema::KitParadigm;

    if kit.paradigm == KitParadigm::Panel {
        // The Transform's manifest names its baked variants; every other
        // installed glb is a source PIECE. No manifest = no bake yet.
        let manifest: Option<super::schema::TransformManifest> =
            std::fs::read_to_string(repo.join(&kit.install_dir).join("manifest.toml"))
                .ok()
                .map(|s| {
                    toml::from_str(&s).unwrap_or_else(|e| {
                        panic!("kit '{key}': manifest.toml does not parse: {e}")
                    })
                });
        let declared = manifest.map(|m| m.variants).unwrap_or_default();

        let files = gltf_files(&repo.join(&kit.install_dir));
        let mut pieces: BTreeMap<String, super::schema::GeneratedPieceRaw> = BTreeMap::new();
        let mut variants: BTreeMap<String, super::schema::GeneratedVariantRaw> = BTreeMap::new();
        for f in &files {
            let stem = f.file_stem().unwrap().to_string_lossy().into_owned();
            match declared.get(&stem) {
                Some(d) => {
                    variants.insert(stem, variant_census(f, d, &kit.detail_flip));
                }
                None => {
                    pieces.insert(stem, piece_census(f));
                }
            }
        }
        for stem in declared.keys() {
            assert!(
                variants.contains_key(stem),
                "kit '{key}': manifest declares '{stem}' but no such glb is installed"
            );
        }
        let square = |p: &&super::schema::GeneratedPieceRaw| -> bool {
            (p.face[0] - p.face[1]) <= 0.01 * p.face[0]
        };
        let pitch = pieces
            .values()
            .filter(square)
            .map(|p| p.face[0])
            .fold(0.0_f32, f32::max);
        assert!(
            pitch > 0.0,
            "kit '{key}': no square plate to derive a grid from — \
             a panel kit needs at least one"
        );
        let snapped = (pitch * 100.0).round() / 100.0;
        return GeneratedKitRaw {
            tile: snapped,
            story: snapped,
            pieces,
            variants,
        };
    }

    let install_dir = &kit.install_dir;
    let res_prefix = format!(
        "res://{}/",
        install_dir.trim_start_matches("godot/").trim_end_matches('/')
    );
    let mut grids: Vec<(String, f32, f32)> = Vec::new();

    for ws in ALL_WALL_SETS {
        if !ws.straight.wall.starts_with(&res_prefix) {
            continue;
        }
        let (wlo, whi) = aabb_bounds(&res_to_disk(repo, ws.straight.wall));
        let (_, chi) = aabb_bounds(&res_to_disk(repo, ws.straight.ceiling));
        grids.push((format!("wall set '{}'", ws.id), whi[2] - wlo[2], chi[1]));
    }

    let (first_src, mut tile, mut story) = grids
        .first()
        .unwrap_or_else(|| {
            panic!("kit '{key}': no recipe (wall set) covers {install_dir}")
        })
        .clone();
    // The grid step is what pieces SNAP to: sets may carry small decorative
    // overhangs (the window set's top lips 2 cm past the others), so agree
    // within 5 cm and take the minimum — a lip overlaps the next course
    // harmlessly, a gap would not.
    for (src, t, s) in &grids {
        assert!(
            (t - tile).abs() < super::schema::GRID_SNAP
                && (s - story).abs() < super::schema::GRID_SNAP,
            "kit '{key}': {src} derives {t:.2}/{s:.2} but {first_src} derives \
             {tile:.2}/{story:.2} — the kit's sets disagree on the grid"
        );
        tile = tile.min(*t);
        story = story.min(*s);
    }
    // Snap to the centimeter: meshes run a hair under their grid (the split
    // panels decimate to 2.997), and the grid is the SNAP step, not the
    // mesh — sub-cm slack is seam tolerance the assembler already absorbs.
    GeneratedKitRaw {
        tile: (tile * 100.0).round() / 100.0,
        story: (story * 100.0).round() / 100.0,
        pieces: Default::default(),
        variants: Default::default(),
    }
}

/// Each kit's grid, derived from recipe + installed meshes.
pub fn kit_grids() -> String {
    let repo = repo_root();
    let kits_file: KitsFile =
        toml::from_str(super::KITS_TOML).expect("kits.toml parses (the loader pins this)");
    let kits: BTreeMap<String, GeneratedKitRaw> = kits_file
        .kits
        .iter()
        // Fixed kits have no recipe to derive a grid from — their pitch is
        // the declared scale (the one authored-grid exception, see kits.toml).
        .filter(|(_, kit)| kit.paradigm != super::schema::KitParadigm::Fixed)
        .map(|(key, kit)| (key.clone(), derive_kit_grid(&repo, key, kit)))
        .collect();
    let body = toml::to_string(&GeneratedKitsFile { kits }).expect("serialize kit grids");
    format!(
        "{GENERATED_HEADER}\
         # Each kit's grid, DERIVED from its assembly recipe: layered kits\n\
         # from the straight wall's width and the top layer's mesh-space\n\
         # y-max (pieces bake their stack position); panel kits from the\n\
         # pool's uniform square extent. No dimension is ever authored.\n\
         \n{body}"
    )
}

#[cfg(test)]
mod tests {
    // --- face_coverage: the solid-vs-truss discriminator ---

    #[test]
    fn a_solid_plate_covers_its_face() {
        // Two triangles tiling the unit square.
        let tris = [
            [[0.0, 0.0], [1.0, 0.0], [1.0, 1.0]],
            [[0.0, 0.0], [1.0, 1.0], [0.0, 1.0]],
        ];
        let c = super::face_coverage(&tris, [0.0, 0.0], [1.0, 1.0]);
        assert!(c > 0.98, "a tiling pair of triangles is a solid plate (got {c})");
    }

    #[test]
    fn a_half_plate_covers_half() {
        let tris = [[[0.0, 0.0], [1.0, 0.0], [1.0, 1.0]]];
        let c = super::face_coverage(&tris, [0.0, 0.0], [1.0, 1.0]);
        assert!((c - 0.5).abs() < 0.05, "one diagonal half-plate (got {c})");
    }

    #[test]
    fn edge_on_slivers_do_not_count() {
        let tris = [[[0.0, 0.0], [1.0, 0.0], [1.0, 1e-9]]];
        let c = super::face_coverage(&tris, [0.0, 0.0], [1.0, 1.0]);
        assert!(c < 0.02, "projected-edge-on slivers are not coverage (got {c})");
    }

    #[test]
    fn an_empty_face_covers_nothing() {
        assert_eq!(super::face_coverage(&[], [0.0, 0.0], [1.0, 1.0]), 0.0);
    }

    /// The emitted kit grids carry a census entry for EVERY installed
    /// piece of every panel kit — expectations derived from kits.toml and
    /// the install dirs themselves (the models-catalog contract shape).
    #[test]
    fn panel_kit_census_covers_every_installed_piece() {
        let parsed: super::GeneratedKitsFile =
            toml::from_str(&super::kit_grids()).expect("emitted kit grids parse");
        let kits_file: super::KitsFile =
            toml::from_str(super::super::KITS_TOML).expect("kits.toml parses");
        for (key, kit) in kits_file
            .kits
            .iter()
            .filter(|(_, k)| k.paradigm == super::super::schema::KitParadigm::Panel)
        {
            let dir = super::repo_root().join(&kit.install_dir);
            let files = super::gltf_files(&dir);
            assert!(!files.is_empty(), "panel kit '{key}' has no installed pieces");
            let generated = parsed
                .kits
                .get(key)
                .unwrap_or_else(|| panic!("panel kit '{key}' missing from grids"));
            assert_eq!(
                generated.pieces.len() + generated.variants.len(),
                files.len(),
                "kit '{key}': census entries (pieces + variants) != installed glbs"
            );
            for f in files {
                let stem = f.file_stem().unwrap().to_string_lossy().into_owned();
                // Every installed glb is censused exactly once: manifest-
                // declared files as VARIANTS, everything else as PIECES.
                if let Some(v) = generated.variants.get(&stem) {
                    assert!(
                        v.face[0] >= v.face[1] && v.face[1] > 0.0,
                        "kit '{key}' variant '{stem}': face extents ordered and positive"
                    );
                    assert!(
                        (0.0..=1.0).contains(&v.coverage),
                        "kit '{key}' variant '{stem}': coverage is a fraction"
                    );
                    assert!(!v.sources.is_empty(), "kit '{key}' variant '{stem}': has sources");
                    assert!(v.tris > 0, "kit '{key}' variant '{stem}': has geometry");
                    continue;
                }
                let piece = generated
                    .pieces
                    .get(&stem)
                    .unwrap_or_else(|| panic!("kit '{key}': piece '{stem}' not censused"));
                assert!(
                    piece.face[0] >= piece.face[1] && piece.face[1] > 0.0,
                    "kit '{key}' piece '{stem}': face extents ordered and positive"
                );
                assert!(
                    (0.0..=1.0).contains(&piece.coverage),
                    "kit '{key}' piece '{stem}': coverage is a fraction"
                );
                assert!(piece.tris > 0, "kit '{key}' piece '{stem}': has geometry");
            }
        }
    }

    /// Transform v2's bake contract: every piece that QUALIFIES for the
    /// wall pool has all three surface-role variants baked from it —
    /// declared in the manifest, installed, censused. The role pools the
    /// v2 assembler consumes can only be as complete as this bake.
    #[test]
    fn qualifying_solids_bake_all_three_surface_roles() {
        use super::super::schema::VariantRole;
        let parsed: super::GeneratedKitsFile =
            toml::from_str(&super::kit_grids()).expect("emitted kit grids parse");
        let kits_file: super::KitsFile =
            toml::from_str(super::super::KITS_TOML).expect("kits.toml parses");
        let mut missing = Vec::new();
        for (key, kit) in kits_file.kits.iter() {
            let Some(bar) = kit.wall_coverage else { continue };
            let generated = parsed
                .kits
                .get(key)
                .unwrap_or_else(|| panic!("panel kit '{key}' missing from grids"));
            for (stem, piece) in &generated.pieces {
                if !piece.qualifies_for_role_bake(generated.tile, bar) {
                    continue;
                }
                for role in [VariantRole::Floor, VariantRole::Ceiling, VariantRole::Wall] {
                    use super::super::schema::ThinAxis;
                    use crate::room_template::ConnectorFacing;
                    let expected = match role {
                        VariantRole::Floor => (ThinAxis::Y, ConnectorFacing::PosY),
                        VariantRole::Ceiling => (ThinAxis::Y, ConnectorFacing::NegY),
                        VariantRole::Wall => (ThinAxis::Z, ConnectorFacing::PosZ),
                        _ => unreachable!(),
                    };
                    match generated
                        .variants
                        .values()
                        .find(|v| v.role == role && v.sources == [stem.clone()])
                    {
                        None => missing.push(format!(
                            "kit '{key}' piece '{stem}': no {role:?} variant baked"
                        )),
                        Some(v) if (v.axis, v.detail) != expected => missing.push(format!(
                            "kit '{key}' piece '{stem}': {role:?} variant mis-baked \
                             — expected thin-{:?}/{:?}, measured thin-{:?}/{:?}",
                            expected.0, expected.1, v.axis, v.detail
                        )),
                        Some(_) => {}
                    }
                }
            }
        }
        assert!(
            missing.is_empty(),
            "qualifying solids without baked role variants (run the \
             Transform — scripts/split-panels.py — then `make assets`):\n{}",
            missing.join("\n")
        );
    }

    /// The relief measure: find the base slab (peak flat-area depth
    /// bin), then weigh geometry BEYOND it on each side. The heavier
    /// side is the artist's greeble — the measure reads the actual
    /// semantic, where the old winding sum read a modeling convention
    /// (the bake 5/6/8 oscillation saga).
    #[test]
    fn relief_masses_point_at_the_greebled_side() {
        // An s×s quad lying flat at height z, as two triangles.
        fn quad(z: f32, s: f32) -> [[[f32; 3]; 3]; 2] {
            [
                [[0.0, 0.0, z], [s, 0.0, z], [s, s, z]],
                [[0.0, 0.0, z], [s, s, z], [0.0, s, z]],
            ]
        }
        let mut tris = quad(0.0, 3.0).to_vec();
        tris.extend(quad(0.5, 1.0));
        let (pos, neg) = super::relief_split(&tris, 2);
        assert!(
            pos > 0.0 && neg == 0.0,
            "greeble above the slab reads positive: pos {pos} neg {neg}"
        );
        let mut tris = quad(0.0, 3.0).to_vec();
        tris.extend(quad(-0.5, 1.0));
        let (pos, neg) = super::relief_split(&tris, 2);
        assert!(
            neg > 0.0 && pos == 0.0,
            "greeble below the slab reads negative: pos {pos} neg {neg}"
        );
        let tris = quad(0.0, 3.0).to_vec();
        let (pos, neg) = super::relief_split(&tris, 2);
        assert!(
            pos == 0.0 && neg == 0.0,
            "a bare slab has no relief: pos {pos} neg {neg}"
        );
    }

    /// Mean of one channel across interleaved pixel bytes — how the
    /// census reads what a metallic-roughness map actually carries
    /// (glTF: green = roughness, blue = metallic), where factors alone
    /// can lie in both directions.
    #[test]
    fn channel_mean_reads_one_interleaved_channel() {
        // Two RGBA pixels: blue channel 0 and 255 — mean 0.5.
        let px = [10u8, 20, 0, 255, 30, 40, 255, 255];
        let blue = super::channel_mean(&px, 4, 2);
        assert!((blue - 0.5).abs() < 1e-3, "blue mean: {blue}");
        // A channel past the stride is absent: neutral 1.0.
        assert_eq!(super::channel_mean(&px, 2, 2), 1.0, "absent channel is neutral");
    }

    /// The authored per-piece flip is only measurable when a baked file's
    /// sources agree on it: all overridden inverts the record, none keeps
    /// it, and a MIXED stack has no single artist front — the probe must
    /// refuse to guess.
    #[test]
    fn authored_flips_must_cover_whole_variants() {
        let sources = ["a".to_string(), "b".to_string()];
        let both = vec!["a".to_string(), "b".to_string()];
        let none: Vec<String> = Vec::new();
        let one = vec!["a".to_string()];
        assert_eq!(super::override_inversion(&sources, &both), Ok(true));
        assert_eq!(super::override_inversion(&sources, &none), Ok(false));
        assert!(
            super::override_inversion(&sources, &one).is_err(),
            "a stack mixing overridden and plain sources is unmeasurable"
        );
    }

    /// kits.toml authors facing per PIECE — a stem list, the escape
    /// hatch for pieces whose relief measurement is structurally
    /// ambiguous. (The kit-wide bool it replaces asserted one bit for
    /// every piece and silently inverted the exceptions — the marble
    /// backs of 2026-07-19.)
    #[test]
    fn a_kit_authors_per_piece_detail_flips() {
        let kits: super::KitsFile = toml::from_str(
            "[kits.k]\n\
             paradigm = \"panel\"\n\
             install_dir = \"godot/addons/walls\"\n\
             wall_coverage = 0.9\n\
             detail_flip = [\"sf_pp01_d_003\"]\n",
        )
        .expect("a stem list parses");
        assert_eq!(kits.kits["k"].detail_flip, ["sf_pp01_d_003".to_string()]);
    }

    /// Every Fixture slot resolves to an installed file — the closed-set
    /// scene table stays machine-checked, never folklore.
    #[test]
    fn fixture_scenes_are_installed() {
        for (fixture, res) in super::super::catalog::FIXTURE_PATHS {
            let disk = super::res_to_disk(&super::repo_root(), res);
            assert!(
                disk.is_file(),
                "{fixture:?}: {res} is not installed (run `make assets`)"
            );
        }
    }

    /// The emitted environment catalog covers every installed environment
    /// scene, one entry per file, keyed by stem — expectations derived from
    /// the install dirs themselves, mirroring the models contract.
    #[test]
    fn installed_environments_are_catalogued() {
        let parsed: super::EnvironmentsFile =
            toml::from_str(&super::environment_catalog()).expect("emitted catalog parses");
        let godot = super::repo_root().join("godot");
        let mut expected = 0;
        for rel in super::ENVIRONMENT_DIRS {
            for f in super::gltf_files(&godot.join(rel)) {
                expected += 1;
                let key = f.file_stem().unwrap().to_string_lossy().into_owned();
                let res = parsed
                    .environments
                    .get(&key)
                    .unwrap_or_else(|| panic!("installed environment '{key}' not catalogued"));
                assert_eq!(
                    super::res_to_disk(&super::repo_root(), res),
                    f,
                    "catalog entry '{key}' points at the wrong file"
                );
            }
        }
        assert_eq!(
            parsed.environments.len(),
            expected,
            "catalog carries entries for files that are not installed"
        );
    }

    #[test]
    #[ignore = "debug instrumentation — run by hand with --nocapture"]
    fn debug_mesh_space_bounds() {
        for rel in [
            "godot/addons/quaternius/modularscifimegakit/walls/TopAstra_Straight.gltf",
            "godot/addons/quaternius/modularscifimegakit/walls/WallAstra_Straight.gltf",
            "godot/addons/quaternius/modularscifimegakit/walls/ShortWall_AccentStrip_Straight.gltf",
            "godot/addons/quaternius/modularscifimegakit/walls/BottomAccent_Straight.gltf",
            "godot/addons/walls/sf_pp01_a_001.glb",
            "godot/addons/walls/sf_pp01_d_001.glb",
            "godot/addons/walls/sf_pp01_f_001.glb",
            "godot/addons/walls_vol3/sf_pp03_m_001.glb",
            "godot/addons/walls_vol3/sf_pp03_n_001.glb",
        ] {
            let (lo, hi) = super::aabb_bounds(&super::repo_root().join(rel));
            println!(
                "{rel}\n  x {:6.2}..{:6.2}  y {:6.2}..{:6.2}  z {:6.2}..{:6.2}",
                lo[0], hi[0], lo[1], hi[1], lo[2], hi[2]
            );
        }
    }

    /// Material factors of the wall-pool plates — run by hand when a
    /// lighting/reflection question needs the glTF facts.
    #[test]
    #[ignore = "debug instrumentation — run by hand with --nocapture"]
    fn debug_plate_materials() {
        for rel in [
            "godot/addons/walls/sf_pp01_d_001.glb",
            "godot/addons/walls/sf_pp01_f_001.glb",
            "godot/addons/walls_vol3/sf_pp03_m_001.glb",
            "godot/addons/walls_vol3/sf_pp03_n_001.glb",
        ] {
            let path = super::repo_root().join(rel);
            let doc = gltf::Gltf::open(&path)
                .unwrap_or_else(|e| panic!("{rel}: {e}"))
                .document;
            for (i, mat) in doc.materials().enumerate() {
                let pbr = mat.pbr_metallic_roughness();
                println!(
                    "{rel} mat {i}: metallic={} rough={} metallic_tex={} base_tex={}",
                    pbr.metallic_factor(),
                    pbr.roughness_factor(),
                    pbr.metallic_roughness_texture().is_some(),
                    pbr.base_color_texture().is_some(),
                );
            }
        }
    }

    #[test]
    #[ignore = "writes rosters/*.generated.toml — `make assets` runs it"]
    fn probe_installed_assets() {
        let catalog = super::repo_root().join("catalog");
        std::fs::write(catalog.join("models.generated.toml"), super::model_catalog())
            .expect("write models.generated.toml");
        std::fs::write(catalog.join("kits.generated.toml"), super::kit_grids())
            .expect("write kits.generated.toml");
        std::fs::write(
            catalog.join("environments.generated.toml"),
            super::environment_catalog(),
        )
        .expect("write environments.generated.toml");
    }
}
