#!/usr/bin/env python3
"""The credits page, rendered from catalog/attributions.toml — the one
place every third-party source's license and required credit line live
(owner 2026-09-09: "we need to start producing a credits page"). The
page is generated, never hand-edited: `make credits` writes
docs/CREDITS.md, and the audit holds the committed page to the render
so a source added to the catalog cannot ship uncredited.

Usage: credits.py <attributions.toml> <out.md>"""
import sys

try:
    import tomllib
except ImportError:  # the audit venv (python 3.9) carries tomli
    import tomli as tomllib

REQUIRED = ("key", "name", "author", "license", "credit", "used_for")


def load(text):
    return tomllib.loads(text)


def render(doc):
    """Markdown, one section per source in name order. A source missing
    a required field is a hole the render refuses: we cannot ship what
    we cannot credit."""
    sources = doc.get("source", [])
    for source in sources:
        missing = [k for k in REQUIRED if not source.get(k)]
        if missing:
            raise ValueError(
                f"attribution {source.get('key', '?')!r} lacks {', '.join(missing)} — "
                f"a third-party source we cannot credit is one we cannot ship")
    lines = [
        "<!-- GENERATED by scripts/credits.py from catalog/attributions.toml "
        "(make credits) — do not edit; add or correct a source in the catalog. -->",
        "# Credits",
        "",
        "Third-party work this game ships or was built from, with the license",
        "each came under and the credit it asks for.",
        "",
    ]
    for source in sorted(sources, key=lambda s: s["name"].lower()):
        unverified = source.get("verified") is False
        lines += [
            f"## {source['name']}",
            "",
            f"- Author: {source['author']}",
            f"- Used for: {source['used_for']}",
            f"- License: {source['license']}"
            + ("  *(license line still to be verified at the source)*" if unverified else ""),
            f"- Credit: {source['credit']}",
        ]
        if source.get("url"):
            lines.append(f"- Source: {source['url']}")
        lines.append("")
    return "\n".join(lines)


def main(attributions_path, out_path):
    with open(attributions_path, encoding="utf-8") as f:
        page = render(load(f.read()))
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(page)
    print(f"credits: {out_path} rendered from {attributions_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main(*sys.argv[1:3]))
