"""Hull + cockpit-shell census for `make assets` (pure Python, no Blender).

    python3 scripts/hull-census.py <hull.glb> <shell.glb> <out.toml>

Written by install-addons.sh right after every cockpit extraction, one
file per hull under out/census/: what the pipeline PRODUCED, in one
stable, human-readable place — the hull's parts with their roster-frame
AABBs, its exported materials (alpha mode, sidedness, textured or flat),
any animations that survived, the cockpit plan the rule derived for it,
and the shell's own parts and eyepoint. Read this instead of parsing a
.glb by hand: the census is reproducible, an inline parse is not.

The audit (`make test-assets`) holds the artifacts to the rule; the
census is the reading aid beside it. Everything here is DERIVED through
the same oracle the audit uses (cockpit_plan.parse_glb / plan_cockpit).
"""
import json
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from cockpit_plan import parse_glb, plan_cockpit  # noqa: E402


def glb_json(path):
    with open(path, "rb") as f:
        _magic, _version, _length = struct.unpack("<III", f.read(12))
        clen, _ctype = struct.unpack("<II", f.read(8))
        return json.loads(f.read(clen))


def toml_str(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def toml_vec(v):
    return "[" + ", ".join(f"{x:.3f}" for x in v) + "]"


def toml_strs(seq):
    return "[" + ", ".join(toml_str(s) for s in seq) + "]"


def toml_bool(b):
    return "true" if b else "false"


def materials_of(gltf):
    rows = []
    for m in gltf.get("materials", []):
        pbr = m.get("pbrMetallicRoughness", {})
        strength = (m.get("extensions", {})
                    .get("KHR_materials_emissive_strength", {})
                    .get("emissiveStrength", 1.0))
        rows.append({
            "name": m.get("name", "?"),
            "alpha_mode": m.get("alphaMode", "OPAQUE"),
            "double_sided": m.get("doubleSided", False),
            "base_texture": "baseColorTexture" in pbr,
            "metal_rough_texture": "metallicRoughnessTexture" in pbr,
            "normal_texture": "normalTexture" in m,
            "roughness": pbr.get("roughnessFactor", 1.0),
            "metallic": pbr.get("metallicFactor", 1.0),
            "emissive_strength": strength,
        })
    return rows


def material_lines(rows, table):
    lines = []
    for r in rows:
        lines += [
            f"[[{table}]]",
            f"name = {toml_str(r['name'])}",
            f"alpha_mode = {toml_str(r['alpha_mode'])}",
            f"double_sided = {toml_bool(r['double_sided'])}",
            f"base_texture = {toml_bool(r['base_texture'])}",
            f"metal_rough_texture = {toml_bool(r['metal_rough_texture'])}",
            f"normal_texture = {toml_bool(r['normal_texture'])}",
            f"roughness = {r['roughness']:.3f}",
            f"metallic = {r['metallic']:.3f}",
            f"emissive_strength = {r['emissive_strength']:.3f}",
            "",
        ]
    return lines


def main(hull_path, shell_path, out_path):
    hull = glb_json(hull_path)
    parts = parse_glb(hull_path)
    plan = plan_cockpit(parts)
    kept = set(plan["keep"])
    lo, hi = plan["volume"]

    lines = [
        "# GENERATED by scripts/hull-census.py (make assets) — do not edit.",
        "# What the pipeline produced for one hull: parts in the roster frame",
        "# (Y up, meters, nose +Z), exported materials, surviving animations,",
        "# the cockpit plan the rule derived, and the built shell.",
        "",
        f"hull = {toml_str(hull_path)}",
        f"shell = {toml_str(shell_path)}",
        f"animations = {toml_strs(a.get('name', '?') for a in hull.get('animations', []))}",
        "",
        "[plan]",
        f"canopy = {toml_str(plan['canopy'])}",
        f"eyepoint = {toml_vec(plan['eyepoint'])}",
        f"volume_lo = {toml_vec(lo)}",
        f"volume_hi = {toml_vec(hi)}",
        f"keep = {toml_strs(plan['keep'])}",
        f"drop = {toml_strs(plan['drop'])}",
        "",
    ]
    for p in parts:
        lines += [
            "[[part]]",
            f"name = {toml_str(p['name'])}",
            f"tris = {p['tris']}",
            f"distinct_solid_tris = {p['distinct_solid_tris']}",
            f"blend = {toml_bool(p['blend'])}",
            f"kept = {toml_bool(p['name'] in kept)}",
            f"lo = {toml_vec(p['lo'])}",
            f"hi = {toml_vec(p['hi'])}",
            "",
        ]
    lines += material_lines(materials_of(hull), "material")

    if os.path.isfile(shell_path):
        shell = glb_json(shell_path)
        shell_parts = parse_glb(shell_path)
        eyes = [n for n in shell.get("nodes", [])
                if "mesh" not in n and n.get("name") == "Eyepoint"]
        eye = eyes[0].get("translation", [0.0, 0.0, 0.0]) if eyes else None
        lines += [
            "[shell_summary]",
            f"parts = {toml_strs(p['name'] for p in shell_parts)}",
            f"tris = {sum(p['tris'] for p in shell_parts)}",
            f"eyepoint_nodes = {len(eyes)}",
        ]
        if eye is not None:
            lines.append(f"eyepoint = {toml_vec(eye)}")
        lines.append("")
        lines += material_lines(materials_of(shell), "shell_material")
    else:
        lines += ["[shell_summary]", "missing = true", ""]

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(
        f"hull-census: {len(parts)} parts, {len(kept)} kept, "
        f"{len(hull.get('animations', []))} animations -> {out_path}"
    )


if __name__ == "__main__":
    main(*sys.argv[1:4])
