//! The asset probe: the final accounting step of `make assets`. It writes
//! `rosters/models.generated.toml` — every installed enemy model, keyed by
//! file stem, valued by its `res://` path. `[[enemy]] model = "<key>"`
//! resolves against this catalog, so a typo or a missing install is a link
//! error naming the culprit — never an invisible drone at runtime. Every
//! catalogued file's geometry is parsed, so a broken export from ANY
//! pipeline step fails the probe, not a run.
//!
//! The output is GENERATED-BUT-COMMITTED (like `VOCABULARY.md`): the game
//! embeds it at compile time, machinery rewrites it, hands never do.
//! Emission goes through the same serde schema the loader reads
//! ([`schema::ModelsFile`]), so the round-trip cannot drift.
//!
//! It also writes `rosters/kits.generated.toml` — each kit's tile/story
//! DERIVED from its assembly recipe (owner 2026-07-05: no authored
//! dimensions anywhere; two hand-transcribed copies had already drifted
//! into folklore). Kit pieces bake their stack position into mesh space,
//! so for a layered kit the story is the TOP layer's y-max (a Top piece
//! spans y 3..5) and the tile is the straight wall's z-range; for a panel
//! kit the pool's uniform square extent is the pitch. The recipes are the
//! wall/panel sets in [`crate::asset_catalog`]; every set of a kit must
//! derive the same grid or the probe fails.
//!
//! Test-gated: the `gltf` parser is a dev-dependency; the probe runs as an
//! `--ignored` writer test (the `regenerate_*` house pattern) from
//! `make assets`.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use crate::asset_catalog::{ALL_PANEL_SETS, ALL_WALL_SETS};

use super::schema::{EnvironmentsFile, GeneratedKitRaw, GeneratedKitsFile, KitsFile, ModelsFile};

/// Where enemy models install, relative to `godot/`. A new directory in
/// the pipeline gets catalogued by being added here.
const MODEL_DIRS: &[&str] = &["addons/enemies", "addons/quaternius/essentials/enemies"];

/// Where fixed-level environment scenes install, relative to `godot/`.
/// Catalogued into `rosters/environments.generated.toml` — a separate
/// namespace from the enemy models (see [`schema::EnvironmentsFile`]).
const ENVIRONMENT_DIRS: &[&str] = &["addons/environments"];

const GENERATED_HEADER: &str =
    "# GENERATED by `make assets` (the roster probe) — do not edit.\n";

fn repo_root() -> PathBuf {
    Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/../..")).to_path_buf()
}

fn gltf_files(dir: &Path) -> Vec<PathBuf> {
    let mut files: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("{}: unreadable ({e}) — run `make assets`", dir.display()))
        .map(|e| e.expect("dir entry").path())
        .filter(|p| {
            p.extension()
                .is_some_and(|x| x == "glb" || x == "gltf")
        })
        .collect();
    files.sort();
    files
}

/// World-space AABB extents (x, y, z) of a glTF file's default scene.
fn aabb_extents(path: &Path) -> [f32; 3] {
    let (lo, hi) = aabb_bounds(path);
    [hi[0] - lo[0], hi[1] - lo[1], hi[2] - lo[2]]
}

/// World-space AABB corners (lo, hi) of a glTF file's default scene:
/// accessor min/max corners composed through the node transforms — bounds
/// come from the JSON, no buffer loading. Kit pieces bake their stack
/// offsets into mesh space (a Top piece SPANS y 3..5), so lo/hi carry
/// assembly information the extents alone lose.
fn aabb_bounds(path: &Path) -> ([f32; 3], [f32; 3]) {
    let doc = gltf::Gltf::open(path)
        .unwrap_or_else(|e| panic!("{}: not a readable glTF ({e})", path.display()))
        .document;
    let mut lo = [f32::INFINITY; 3];
    let mut hi = [f32::NEG_INFINITY; 3];

    // Column-major, matching gltf::scene::Transform::matrix().
    fn mul(a: [[f32; 4]; 4], b: [[f32; 4]; 4]) -> [[f32; 4]; 4] {
        let mut out = [[0.0; 4]; 4];
        for (c, col) in out.iter_mut().enumerate() {
            for (r, cell) in col.iter_mut().enumerate() {
                *cell = (0..4).map(|k| a[k][r] * b[c][k]).sum();
            }
        }
        out
    }

    fn visit(
        node: gltf::Node,
        parent: [[f32; 4]; 4],
        lo: &mut [f32; 3],
        hi: &mut [f32; 3],
        path: &Path,
    ) {
        let world = mul(parent, node.transform().matrix());
        if let Some(mesh) = node.mesh() {
            for prim in mesh.primitives() {
                let Some(acc) = prim.get(&gltf::Semantic::Positions) else {
                    continue;
                };
                let corner = |v: &serde_json::Value, i: usize| -> f32 {
                    v.get(i).and_then(|x| x.as_f64()).unwrap_or_else(|| {
                        panic!("{}: POSITION accessor without bounds", path.display())
                    }) as f32
                };
                let (min, max) = (
                    acc.min().expect("POSITION min is required by the glTF spec"),
                    acc.max().expect("POSITION max is required by the glTF spec"),
                );
                for cx in [corner(&min, 0), corner(&max, 0)] {
                    for cy in [corner(&min, 1), corner(&max, 1)] {
                        for cz in [corner(&min, 2), corner(&max, 2)] {
                            for i in 0..3 {
                                let p = world[0][i] * cx
                                    + world[1][i] * cy
                                    + world[2][i] * cz
                                    + world[3][i];
                                lo[i] = lo[i].min(p);
                                hi[i] = hi[i].max(p);
                            }
                        }
                    }
                }
            }
        }
        for child in node.children() {
            visit(child, world, lo, hi, path);
        }
    }

    let identity = [
        [1.0, 0.0, 0.0, 0.0],
        [0.0, 1.0, 0.0, 0.0],
        [0.0, 0.0, 1.0, 0.0],
        [0.0, 0.0, 0.0, 1.0],
    ];
    let scene = doc
        .default_scene()
        .or_else(|| doc.scenes().next())
        .unwrap_or_else(|| panic!("{}: no scene", path.display()));
    for node in scene.nodes() {
        visit(node, identity, &mut lo, &mut hi, path);
    }
    assert!(
        lo[0].is_finite(),
        "{}: no positioned geometry",
        path.display()
    );
    (lo, hi)
}

/// The model catalog: every installed enemy model, geometry-validated.
pub fn model_catalog() -> String {
    let godot = repo_root().join("godot");
    let mut models = BTreeMap::new();
    for rel in MODEL_DIRS {
        for f in gltf_files(&godot.join(rel)) {
            aabb_extents(&f); // a broken export fails the probe, not a run
            let key = f.file_stem().unwrap().to_string_lossy().into_owned();
            let res = format!(
                "res://{}",
                f.strip_prefix(&godot).unwrap().display()
            );
            assert!(
                models.insert(key.clone(), res).is_none(),
                "duplicate model key '{key}' across the install dirs"
            );
        }
    }
    let body = toml::to_string(&ModelsFile { models }).expect("serialize model catalog");
    format!(
        "{GENERATED_HEADER}\
         # Every installed enemy model: key (file stem) -> res:// path.\n\
         # rosters/enemies.toml refers to models by KEY; the linker resolves\n\
         # against this catalog, so a bad reference fails the load, loudly.\n\
         \n{body}"
    )
}

/// The environment catalog: every installed fixed-level environment scene,
/// geometry-validated.
pub fn environment_catalog() -> String {
    let godot = repo_root().join("godot");
    let mut environments = BTreeMap::new();
    for rel in ENVIRONMENT_DIRS {
        for f in gltf_files(&godot.join(rel)) {
            aabb_extents(&f); // a broken export fails the probe, not a run
            let key = f.file_stem().unwrap().to_string_lossy().into_owned();
            let res = format!("res://{}", f.strip_prefix(&godot).unwrap().display());
            assert!(
                environments.insert(key.clone(), res).is_none(),
                "duplicate environment key '{key}' across the install dirs"
            );
        }
    }
    let body =
        toml::to_string(&EnvironmentsFile { environments }).expect("serialize environment catalog");
    format!(
        "{GENERATED_HEADER}\
         # Every installed fixed-level environment: key (file stem) -> res://\n\
         # path. Fixed-paradigm kits refer to environments by KEY; the linker\n\
         # resolves against this catalog, so a bad reference fails the load,\n\
         # loudly.\n\
         \n{body}"
    )
}

/// A res:// path's location on disk.
fn res_to_disk(repo: &Path, res: &str) -> PathBuf {
    repo.join("godot").join(res.trim_start_matches("res://"))
}

/// Derive one kit's grid from its recipe sets. Layered: tile = the straight
/// wall's z-range, story = the top layer's mesh-space y-max (pieces bake
/// their stack position, so the ceiling piece's top IS the story). Panel:
/// the pool's uniform square extent. Every set covering the kit must agree.
fn derive_kit_grid(repo: &Path, key: &str, install_dir: &str) -> GeneratedKitRaw {
    let res_prefix = format!(
        "res://{}/",
        install_dir.trim_start_matches("godot/").trim_end_matches('/')
    );
    let mut grids: Vec<(String, f32, f32)> = Vec::new();

    for ws in ALL_WALL_SETS {
        if !ws.straight.wall.starts_with(&res_prefix) {
            continue;
        }
        let (wlo, whi) = aabb_bounds(&res_to_disk(repo, ws.straight.wall));
        let (_, chi) = aabb_bounds(&res_to_disk(repo, ws.straight.ceiling));
        grids.push((format!("wall set '{}'", ws.id), whi[2] - wlo[2], chi[1]));
    }
    for ps in ALL_PANEL_SETS {
        if !ps.panels.first().is_some_and(|p| p.starts_with(&res_prefix)) {
            continue;
        }
        for panel in ps.panels {
            let (lo, hi) = aabb_bounds(&res_to_disk(repo, panel));
            let (w, h) = (hi[0] - lo[0], hi[1] - lo[1]);
            assert!(
                (w - h).abs() < 0.01,
                "panel set '{}': {panel} is {w:.2}x{h:.2} — pool panels must \
                 be square (one cell face each)",
                ps.id
            );
            grids.push((format!("panel set '{}' {panel}", ps.id), w, h));
        }
    }

    let (first_src, mut tile, mut story) = grids
        .first()
        .unwrap_or_else(|| {
            panic!("kit '{key}': no recipe (wall or panel set) covers {install_dir}")
        })
        .clone();
    // The grid step is what pieces SNAP to: sets may carry small decorative
    // overhangs (the window set's top lips 2 cm past the others), so agree
    // within 5 cm and take the minimum — a lip overlaps the next course
    // harmlessly, a gap would not.
    for (src, t, s) in &grids {
        assert!(
            (t - tile).abs() < 0.05 && (s - story).abs() < 0.05,
            "kit '{key}': {src} derives {t:.2}/{s:.2} but {first_src} derives \
             {tile:.2}/{story:.2} — the kit's sets disagree on the grid"
        );
        tile = tile.min(*t);
        story = story.min(*s);
    }
    // Snap to the centimeter: meshes run a hair under their grid (the split
    // panels decimate to 2.997), and the grid is the SNAP step, not the
    // mesh — sub-cm slack is seam tolerance the assembler already absorbs.
    GeneratedKitRaw {
        tile: (tile * 100.0).round() / 100.0,
        story: (story * 100.0).round() / 100.0,
    }
}

/// Each kit's grid, derived from recipe + installed meshes.
pub fn kit_grids() -> String {
    let repo = repo_root();
    let kits_file: KitsFile =
        toml::from_str(super::KITS_TOML).expect("kits.toml parses (the loader pins this)");
    let kits: BTreeMap<String, GeneratedKitRaw> = kits_file
        .kits
        .iter()
        // Fixed kits have no recipe to derive a grid from — their pitch is
        // the declared scale (the one authored-grid exception, see kits.toml).
        .filter(|(_, kit)| kit.paradigm != super::schema::KitParadigm::Fixed)
        .map(|(key, kit)| (key.clone(), derive_kit_grid(&repo, key, &kit.install_dir)))
        .collect();
    let body = toml::to_string(&GeneratedKitsFile { kits }).expect("serialize kit grids");
    format!(
        "{GENERATED_HEADER}\
         # Each kit's grid, DERIVED from its assembly recipe: layered kits\n\
         # from the straight wall's width and the top layer's mesh-space\n\
         # y-max (pieces bake their stack position); panel kits from the\n\
         # pool's uniform square extent. No dimension is ever authored.\n\
         \n{body}"
    )
}

#[cfg(test)]
mod tests {
    /// The emitted environment catalog covers every installed environment
    /// scene, one entry per file, keyed by stem — expectations derived from
    /// the install dirs themselves, mirroring the models contract.
    #[test]
    fn installed_environments_are_catalogued() {
        let parsed: super::EnvironmentsFile =
            toml::from_str(&super::environment_catalog()).expect("emitted catalog parses");
        let godot = super::repo_root().join("godot");
        let mut expected = 0;
        for rel in super::ENVIRONMENT_DIRS {
            for f in super::gltf_files(&godot.join(rel)) {
                expected += 1;
                let key = f.file_stem().unwrap().to_string_lossy().into_owned();
                let res = parsed
                    .environments
                    .get(&key)
                    .unwrap_or_else(|| panic!("installed environment '{key}' not catalogued"));
                assert_eq!(
                    super::res_to_disk(&super::repo_root(), res),
                    f,
                    "catalog entry '{key}' points at the wrong file"
                );
            }
        }
        assert_eq!(
            parsed.environments.len(),
            expected,
            "catalog carries entries for files that are not installed"
        );
    }

    #[test]
    #[ignore = "debug instrumentation — run by hand with --nocapture"]
    fn debug_mesh_space_bounds() {
        for rel in [
            "godot/addons/quaternius/modularscifimegakit/walls/TopAstra_Straight.gltf",
            "godot/addons/quaternius/modularscifimegakit/walls/WallAstra_Straight.gltf",
            "godot/addons/quaternius/modularscifimegakit/walls/ShortWall_AccentStrip_Straight.gltf",
            "godot/addons/quaternius/modularscifimegakit/walls/BottomAccent_Straight.gltf",
            "godot/addons/walls/sf_pp01_a_001.glb",
        ] {
            let (lo, hi) = super::aabb_bounds(&super::repo_root().join(rel));
            println!(
                "{rel}\n  x {:6.2}..{:6.2}  y {:6.2}..{:6.2}  z {:6.2}..{:6.2}",
                lo[0], hi[0], lo[1], hi[1], lo[2], hi[2]
            );
        }
    }

    #[test]
    #[ignore = "writes rosters/*.generated.toml — `make assets` runs it"]
    fn probe_installed_assets() {
        let rosters = super::repo_root().join("rosters");
        std::fs::write(rosters.join("models.generated.toml"), super::model_catalog())
            .expect("write models.generated.toml");
        std::fs::write(rosters.join("kits.generated.toml"), super::kit_grids())
            .expect("write kits.generated.toml");
        std::fs::write(
            rosters.join("environments.generated.toml"),
            super::environment_catalog(),
        )
        .expect("write environments.generated.toml");
    }
}
